version: 2
jobs:
  build:
    working_directory: ~/yolo
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run:
          name: Install build/test dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-dev python3-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run:
          name: Run tox
          command: |
            . venv/bin/activate
            tox
